---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo01
  template:
    metadata:
      annotations:
        service_id : "4538"
        service_name: "ser0"
        service_deadline: "2020-12-10 18:12:11"
        service_running_time: "0"
        service_priority: "0"
        required_service_rate: "300"
        id_vnf: "1"
      labels:
        app: foo01
    spec:
      schedulerName: my-scheduler
      containers:
      - name: foo01
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "300Mi"
            cpu: "100m"
          limits:
            memory: "500M"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo02
  template:
    metadata:
      annotations:
        service_id : "4538"
        service_name: "ser0"
        service_deadline: "2020-12-10 18:12:11"
        service_running_time: "0"
        service_priority: "0"
        required_service_rate: "300"
        id_vnf: "2"
      labels:
        app: foo02
    spec:
      schedulerName: my-scheduler
      containers:
      - name: foo02
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "300Mi"
            cpu: "100m"
          limits:
            memory: "500M"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo03
  template:
    metadata:
      annotations:
        service_id : "4539"
        service_name: "ser1"
        service_deadline: "2020-12-10 17:12:11"
        service_running_time: "0"
        service_priority: "2"
        required_service_rate: "300"
        id_vnf: "1"
      labels:
        app: foo03
    spec:
      schedulerName: my-scheduler
      containers:
      - name: foo03
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "300Mi"
            cpu: "300m"
          limits:
            memory: "500M"
            cpu: "400m"