# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "172.16.2.152"
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
  image: kindest/node:v1.24.2
  extraMounts:
  - hostPath: /usr/share/zoneinfo/Europe/Paris
    containerPath: /etc/localtime
  extraPortMappings:
  - containerPort: 7400
    hostPort: 7400
    listenAddress: "127.0.0.1"
    protocol: UDP
  - containerPort: 7410
    hostPort: 7410
    listenAddress: "127.0.0.1"
    protocol: UDP
  - containerPort: 7411
    hostPort: 7411
    listenAddress: "127.0.0.1"
    protocol: UDP
# the three workers
- role: worker
  image: kindest/node:v1.24.2 #1.19.1
  extraMounts:
  - hostPath: /usr/share/zoneinfo/Europe/Paris
    containerPath: /etc/localtime
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
        name: kubernetes-worker1
- role: worker
  image: kindest/node:v1.24.2
  extraMounts:
  - hostPath: /usr/share/zoneinfo/Europe/Paris
    containerPath: /etc/localtime
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
        name: kubernetes-worker2
- role: worker
  image: kindest/node:v1.24.2
  extraMounts:
  - hostPath: /usr/share/zoneinfo/Europe/Paris
    containerPath: /etc/localtime
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
        name: kubernetes-worker3
